### PR TITLE
#181 Added possibility to declare description for config path.

### PR DESCRIPTION
**Pull request by const1993**

### CODE REVIEW

**Comment by const1993** [comment]
After bqRuntime.declareDescription("x.m", "Test description") the output for -h command will be:
...
OPTIONS
      -c yaml_location, --config=yaml_location
           Specifies YAML config location, which can be a file path or a URL.

      -h, --help
           Prints this message.

      -H, --help-config
           Prints information about application modules and their configuration
           options.

ENVIRONMENT
      m
        Test description

**Comment by andrus** [comment]
@const1993 I understand the new extender method "declareVar", but I need explanation on "declareDescription" and "declareDescriptions". What are those about? Can you explain the use case?

Also there is a typo in the property name: `DeclaredVar.descripption`

**Comment by const1993** [comment]
@andrus I added a javadoc for declareDescriptions. Its needed if you want to add the couple of descriptions for config path. I removed the declareDescription because it was needed only as a transitional method between declareDescriptions and declareVar, which made the lamda in foreach more elegant, but not necessary.

**Comment by andrus** [comment]
I still don't understand why would a user need to document config paths that are not bound to variables? Is this to override the default documentation provided in the modules? Not saying it is not needed, just that it requires more explanation of the use case. I think this warrants a separate task that explains the use case a little better, and this pull request should focus on the variables.

**Comment by const1993** [comment]
The idea was to use it after declare variables. Like this: "extender.declareVars(declaredVars).declareDescriptions(declaredDescriptions);"
It was used in BQInternalTestFactory. I didn't considered that it could be used without declareVariable. 
If we will need such functionality, we should implement some VO for it. 
I removed this method for this PR.

**Comment by andrus** [comment]
Ah, now I get it. Yeah, it will be confusing like this, as builder methods can be called in any order.

**Pull request merged**
