### PR TITLE
Complex command invocation structures

### PR DESCRIPTION
**Pull request by atomashpolskiy**
Relates to #131. This PR is not for merging, but rather for preliminary review. It's still rough on edges and needs more work, but the overall idea should be clear. There's also a simple test, that demonstrates the user-facing API: `io.bootique.Bootique_CommandOverrideIT`.

### CODE REVIEW

**Comment by andrus** [comment]
I think this is going in the right direction. A few API-related suggestions/notes:

*  `BQCoreModuleExtender.addCommandOverride(String, CommandOverride.Builder)` - probably a good idea to add an immutable object, not a builder here (I know we have a bad precedent where we pass a builder to `CommandWithMetadata` constructor. Let's not repeat it here).
* Thinking about the terminology. "Override" sounds a bit too generic to the end user. What she'll be doing is extending what some command does, while override is just an internal mechanism of doing that. So maybe we use "decorate" as a term? E.g. `CommandDecorator`, `addCommandDecorator(..)`, etc.
* Perhaps we should use a command class , not its String name as a key to override/decorator. (I.e. `ServerCommand.class` instead of '--server').
* Micro-optimization: CommandInvocation can take and store its CLI as String[] instead of String, avoiding String parsing during invocation.

**Comment by andrus** [comment]
Another issue that we'll need to resolve is suppressing all these auxiliary commands from appearing in the app help.

**Comment by atomashpolskiy** [comment]
@andrus, addressed your points (except for the --help output)

**Comment by andrus** [comment]
Is it ready for the final review?

**Comment by atomashpolskiy** [comment]
@andrus , yeah, I think it's ready

**Pull request merged**
