### PR TITLE
Use markdown for documenting core module.

### PR DESCRIPTION
**Pull request by IRus**
Was:
image

Become:
image

### CODE REVIEW

**Comment by IRus** [comment]
Also you'll able to preview docs right here: https://github.com/bootique/bootique/blob/842a17b841d4814dbbea028e4b8902b0365bfb10/docs/bootique-docs.md

**Comment by andrus** [comment]
@IRus I merged the PR. A few questions:

* How does the publishing work? Maybe we add a README.md either inside the docs folder, or expand the one under https://github.com/bootique/bootique-io 
* I noticed chapter numbers are now hardcoded and all chapters are in a single file. Is there a way to put chapters in separate files, and assign the numbers dynamically (or via a central index file or something)

**Comment by IRus** [comment]
@andrus 
1. Publishing handles by bootique/bootique-io repository, and described in https://github.com/bootique/bootique-io/blob/master/README.md. So build on travis is publish. 
2. Yes, It possible to separate chapters in different files, I'll do this.

**Comment by andrus** [comment]
Re: 1: Got it, thanks. I guess we may mention it explicitly there ("to publish external documentation" to the site, manually tun travis build" or something).
Re: 2: Great, thanks!

**Pull request merged**
