### PR TITLE
Improvements for Module aggregation / define module dependencies. #183

### PR DESCRIPTION
**Pull request by IRus**
Module aggregation / define module dependencies. #183

### CODE REVIEW

**Comment by IRus** [comment]
I add `BQModule id()` method to `BQModuleProvider` in order to fix [issue](https://github.com/bootique/bootique/issues/191) with identifying different instances of same module class:

```
// TODO: looking up modules by java type limits the use of lambdas as modules. E.g. we loaded test
// properties are dynamically created modules in a repeatedly called Lambda. This didn't work..
// So perhaps use provider name as a unique key?
```

So it helps to merge `BQModuleProvider`s that come from dependency graph, auto-loading and bootique builder (`Bootique.app().module(...)`).  

https://github.com/bootique/bootique/pull/204/files#diff-fc75fb4411338de93aeb75a2d4934914R77

**Comment by IRus** [comment]
Also this PR breaks backward compatibility of `BQModuleProvider` since:

1. Requires new method `BQModuleId id()` to implement;
2. Changes signature of dependencies method.

**Comment by IRus** [comment]
There are still issues with this PR:

1. Should update docs according this changes;
2. Should update CHANGELOG.md.

But let's discuss this solution first, and if you ok with this solution - I'll fix this gap.

**Comment by andrus** [comment]
I did some research in the last few days, and posted [my thoughts](https://groups.google.com/forum/#!topic/bootique-user/KuTVkhYi6O4) on the Bootique forum. I think our current solution in general (not just this pull request) should be superseded by Java `module-info.java`.

**Pull request closed without merging**
